theme: jekyll-theme-architect
title: Teoria dos Números
name: Teoria dos Números
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
bg: black
color: white
